version: "2"

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
  pgadminer:
    image: clue/adminer:latest
    depends_on:
      - postgres
    links:
      - postgres
  flyway:
    image: boxfuse/flyway:latest
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
      - POSTGRES_HOST
    depends_on:
      - postgres
    links:
      - postgres
  app:
    image: jboss/wildfly:latest
    build:
      context: ./docker/app/
      dockerfile: Dockerfile
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_DB
      - POSTGRES_HOST
    depends_on:
      - postgres
    links:
      - postgres
