version: "2"

services:
  app:
    build:
      context: ./docker/app/
      dockerfile: Dockerfile
    container_name: "app"
    environment:
      - WILDFLY_USER=admin
      - WILDFLY_PASS=adminPassword
      - DB_NAME=sample
      - DB_USER=mysql
      - DB_PASS=mysql
      - DB_URI=db:3306
    depends_on:
      - db
    ports:
      - "8080:8080"
      - "9990:9990"
    volumes:
      - "./target:/opt/jboss/wildfly/standalone/deployments"

  db:
    build:
      context: ./docker/db/
      dockerfile: Dockerfile
    container_name: "db"
    environment:
      - MYSQL_DATABASE=sample
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
      - MYSQL_ROOT_PASSWORD=supersecret
    ports:
      - "3306:3306"

networks:
  default:
    driver: bridge