---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracky-app
spec:
  selector:
    matchLabels:
      app: tracky-app
  replicas: 1
  template:
    metadata:
      labels:
        app: tracky-app
    spec:
      containers:
        - name: tracky-node
          image: tracky-node:dev
          imagePullPolicy: Never
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: tracky-app-svc
  labels:
    app: tracky-app
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30803
      protocol: TCP
  selector:
    app: tracky-app
---